/**
 * Long-form evergreen guides — US property tax methodology and decision-making.
 * Hub pages that link deep into the state/county/calculator matrix.
 * Each guide targets a high-intent keyword with state-by-state specificity.
 */

export interface Guide {
  slug: string;
  title: string;
  description: string;
  intro: string; // HTML
  sections: Array<{ heading: string; html: string }>;
  faqs: Array<{ question: string; answer: string }>;
  category: string;
  updatedAt: string;
}

const u = '2026-04-10';

export const guides: Guide[] = [
  {
    slug: 'effective-vs-nominal-property-tax-rates',
    title: 'Effective vs Nominal Property Tax Rates: Why Your "1% Rate" Isn\'t What You Pay',
    description: 'How millage rates, assessment ratios, and exemptions create a 3x gap between the headline tax rate and what homeowners actually pay. A practical guide to reading property tax data correctly.',
    category: 'Tax Mechanics',
    updatedAt: u,
    intro: `<p>The headline number on a property tax page is almost never what you actually pay. A "1.5 percent rate" can translate to anywhere from 0.5 percent to 2 percent of market value depending on the state's assessment ratio, exemption rules, and how the local government calculates the bill. This is the single biggest source of confusion in property tax data, and getting it wrong means budgeting for the wrong number when you buy.</p><p>This guide explains the three components that determine your real tax burden, how to convert any state's published rate into the effective rate that affects your wallet, and which states have the biggest gap between the two.</p>`,
    sections: [
      {
        heading: 'The three numbers you must understand',
        html: `<p>Every property tax bill is the product of three separate numbers, and any one of them can dominate the final amount:</p><ol><li><strong>Market value:</strong> what your home would actually sell for today.</li><li><strong>Assessed value:</strong> the value the local assessor uses for tax purposes. This is often a fraction of market value.</li><li><strong>Millage rate (or mill rate):</strong> the tax per $1,000 of assessed value, set by the county, city, school district, and special districts combined.</li></ol><p>Your annual bill equals: <code>Assessed Value × Total Millage ÷ 1,000</code>. The "tax rate" you see on most websites is usually the millage rate expressed as a percentage of <em>assessed</em> value. The <strong>effective rate</strong> — the rate you actually pay as a percentage of <em>market</em> value — is millage rate × assessment ratio.</p>`,
      },
      {
        heading: 'Why assessment ratios matter so much',
        html: `<p>Assessment ratio is the gap between market value and assessed value, and it varies enormously between states:</p><ul><li><strong>South Carolina:</strong> 4 percent for owner-occupied primary residences. A $400,000 home is assessed at $16,000.</li><li><strong>Alabama:</strong> 10 percent for residential.</li><li><strong>Massachusetts:</strong> 100 percent — assessed value equals market value.</li><li><strong>California:</strong> 100 percent at purchase, but frozen under Proposition 13 (see our <a href="/guide/why-property-taxes-vary-10x/">Prop 13 guide</a>).</li><li><strong>Texas:</strong> 100 percent, with annual reassessment.</li></ul><p>This is why two states with identical "1.5 percent" headline rates can produce wildly different bills. South Carolina's 1.5 percent on 4 percent assessment ratio = an effective 0.06 percent. Texas's 1.5 percent on 100 percent assessment = 1.5 percent flat. That's a 25x difference for the same nominal rate.</p>`,
      },
      {
        heading: 'New Jersey vs Texas: a real comparison',
        html: `<p>New Jersey and Texas are often cited as the "most-taxed" states for property, but the comparison is misleading without effective rates:</p><ul><li><strong>New Jersey:</strong> nominal millage often quoted at 2.5 percent, but assessment ratios in many municipalities run at 80–100 percent of market value. Effective rate: roughly 2.2 to 2.5 percent.</li><li><strong>Texas:</strong> nominal rates of 1.6 to 2.2 percent depending on county, applied to 100 percent of market value. Effective rate: roughly 1.6 to 2.2 percent.</li></ul><p>For a $400,000 home, that translates to:</p><ul><li>NJ: about $9,000 to $10,000 per year</li><li>TX: about $6,400 to $8,800 per year</li></ul><p>The headline "NJ has the highest property tax rate" is technically correct but understates the spread because Texas applies its rate to higher assessed values without exemptions. New Jersey has more aggressive senior and veteran exemptions, which can shrink the gap further for many households.</p>`,
      },
      {
        heading: 'How to convert any state\'s rate to your effective rate',
        html: `<p>Three-step procedure:</p><ol><li><strong>Find the local total millage rate.</strong> This is the sum of county + municipal + school district + special district rates. County assessor websites publish it. We list current totals on our state pages.</li><li><strong>Find the local assessment ratio.</strong> Sometimes called "assessment level," "common level ratio" (PA), or "equalization rate" (NY). Published by the state department of taxation.</li><li><strong>Multiply.</strong> Effective rate = millage × assessment ratio. Apply to your home's market value to get the rough annual bill.</li></ol><p>Example: a Pennsylvania home with a millage of 30 mills (3 percent) and a common level ratio of 0.82 has an effective rate of 2.46 percent. On a $300,000 home, that's about $7,380 per year — assuming no exemptions.</p>`,
      },
      {
        heading: 'Where the published numbers go wrong',
        html: `<p>Most online property tax data has at least one of these flaws:</p><ul><li><strong>Quoting nominal rates without assessment ratios.</strong> Common on real estate sites that pull a single number from county records. Useless for cross-state comparison.</li><li><strong>Using statewide averages that hide huge intra-state variation.</strong> Illinois statewide effective rate is about 2.0 percent, but Cook County (Chicago) is closer to 2.5 percent and rural counties closer to 1.5 percent. The state average misleads in both directions.</li><li><strong>Ignoring exemptions.</strong> The first $50,000 of value is often exempt for primary residences (homestead exemption). For lower-priced homes, exemptions can cut the effective rate in half.</li><li><strong>Mixing taxable and assessed value.</strong> "Taxable value" is assessed value minus exemptions. The "effective rate on market value" is what matters; "effective rate on taxable value" is closer to the nominal rate and looks deceptively low.</li></ul><p>Our <a href="/calculator/">calculator</a> applies the correct math for each state, including the standard homestead exemption, so you can see the real number for your situation.</p>`,
      },
      {
        heading: 'A quick state-rank table by true effective rate',
        html: `<p>Sorted by effective rate on market value (rough current estimates; check our state pages for live data):</p><ul><li><strong>Highest 5:</strong> New Jersey (~2.4%), Illinois (~2.1%), New Hampshire (~2.0%), Connecticut (~2.0%), Vermont (~1.9%)</li><li><strong>Texas band:</strong> Texas (~1.7%), Wisconsin (~1.7%), Nebraska (~1.6%)</li><li><strong>Mid-band:</strong> Ohio, Iowa, Kansas, Pennsylvania, Michigan (1.4–1.6%)</li><li><strong>Sun Belt low:</strong> Florida (~0.9%), Georgia (~0.9%), Arizona (~0.6%)</li><li><strong>Lowest 5:</strong> Hawaii (~0.3%), Alabama (~0.4%), Louisiana (~0.5%), Colorado (~0.5%), Wyoming (~0.6%)</li></ul><p>Hawaii's stunning low rate is real, but the median home costs over $700,000, so the absolute dollar amount is not as low as the rate suggests. Always look at both rate and median home value when judging affordability.</p>`,
      },
    ],
    faqs: [
      { question: 'What is the difference between effective and nominal property tax rate?', answer: 'Nominal rate is the published millage or percentage applied to assessed value. Effective rate is the same tax expressed as a percentage of market value, which is what you actually pay relative to your home\'s real worth. Effective rate is the only fair comparison across states with different assessment systems.' },
      { question: 'Why does my neighbor pay less property tax than I do for a similar home?', answer: 'Several reasons: they may have a homestead exemption you have not claimed, an older assessment under a freeze (like California Prop 13), a senior or veteran exemption, or a successful appeal. We cover this in our guide on tax variation between neighbors.' },
      { question: 'How do I find the assessment ratio for my state?', answer: 'Search for "[your state] department of revenue assessment ratio" or "common level ratio" (Pennsylvania) or "equalization rate" (New York). Most states publish this annually. Our state pages also list the current effective rate.' },
      { question: 'Are property taxes deductible on federal returns?', answer: 'Yes, but capped at $10,000 total state and local taxes (SALT cap) since 2018. For high-tax states like New Jersey, Illinois, and California, this cap means many homeowners can deduct only part of their property tax bill. Check current IRS guidance for any updates.' },
      { question: 'Why do effective rates vary so much within a single state?', answer: 'Local school district funding is the main driver. School districts set their own millage to fund local schools, and a wealthy district with low enrollment can have a much lower rate than an urban district with high enrollment. County and special district rates layer on top.' },
      { question: 'Is a high property tax rate always bad?', answer: 'Not necessarily. High property tax states often fund schools, roads, and services through property tax instead of income or sales tax. A low-property-tax state may have higher state income tax (like California compared to Texas). Compare total tax burden, not just property tax.' },
    ],
  },
  {
    slug: 'state-by-state-property-tax-burden',
    title: 'State-by-State Property Tax Burden: A 50-State Reality Check',
    description: 'The 10 highest and 10 lowest property tax states, with effective rates, median bills, and the hidden factors (assessment caps, exemptions, school funding) that change the picture.',
    category: 'State Comparison',
    updatedAt: u,
    intro: `<p>Property tax varies more between US states than almost any other tax. The highest-rate states (New Jersey, Illinois) charge an effective rate four to seven times higher than the lowest (Hawaii, Alabama). But raw rate is misleading — what matters to homeowners is the dollar amount, which depends equally on rate and median home value. This guide ranks all 50 states by both, explains the structural reasons for the differences, and highlights states where the headline rate hides a much different real burden.</p>`,
    sections: [
      {
        heading: 'The 10 highest-burden states',
        html: `<p>Ranked by effective rate on median home value (current estimates from state revenue departments and ACS data):</p><ol><li><strong>New Jersey — ~2.4% effective.</strong> Median annual property tax bill exceeds $9,000. Top in the country for both rate and absolute dollars on a typical home. Homestead and senior exemptions help, but aggressive school district funding keeps rates high.</li><li><strong>Illinois — ~2.1%.</strong> Cook County (Chicago) is the highest urban county, regularly producing $8,000+ bills on $400,000 homes. Pension funding obligations are the main structural driver.</li><li><strong>New Hampshire — ~2.0%.</strong> No state income tax, no sales tax — property tax funds nearly everything. Bills are high but the trade-off is no withholding from your paycheck.</li><li><strong>Connecticut — ~2.0%.</strong> Funded primarily at the town level, with significant variation between Fairfield County and rural counties.</li><li><strong>Vermont — ~1.9%.</strong> Statewide education property tax pools school funding across the state.</li><li><strong>Wisconsin — ~1.7%.</strong> School district funding via local levy; equalization formulas spread the burden.</li><li><strong>Texas — ~1.7%.</strong> No state income tax (like NH). Property tax fully funds schools, county government, and special districts. Annual reassessment at 100 percent ratio means rising market values translate quickly into higher bills.</li><li><strong>Nebraska — ~1.6%.</strong> Heavy school district reliance.</li><li><strong>Ohio — ~1.5%.</strong> Wide local variation, but no widespread cap on annual increases.</li><li><strong>Iowa — ~1.5%.</strong> Rolling 5-year reassessment caps cushion sudden increases but the base rate is high.</li></ol>`,
      },
      {
        heading: 'The 10 lowest-burden states',
        html: `<ol><li><strong>Hawaii — ~0.27%.</strong> Lowest rate in the country, but median home value over $700,000 means absolute bills are still moderate ($1,900+).</li><li><strong>Alabama — ~0.40%.</strong> 10 percent assessment ratio combined with low millage produces the cheapest absolute bills among populated states.</li><li><strong>Colorado — ~0.50%.</strong> Recent rate reductions following voter initiatives; assessment ratio is one of the lowest.</li><li><strong>Louisiana — ~0.55%.</strong> Generous homestead exemption ($75,000) for primary residences.</li><li><strong>South Carolina — ~0.55%.</strong> 4 percent assessment ratio for owner-occupied homes — the lowest in the country.</li><li><strong>Wyoming — ~0.60%.</strong> Small population spreads modest budgets thin.</li><li><strong>West Virginia — ~0.60%.</strong> Low home values keep absolute bills among the lowest in the country.</li><li><strong>Nevada — ~0.55%.</strong> No state income tax, but property tax is also kept low; gaming revenue covers much of the state budget.</li><li><strong>Utah — ~0.60%.</strong> Owner-occupied homes get a 45 percent reduction in taxable value via the residential exemption.</li><li><strong>Delaware — ~0.55%.</strong> Reassessments are infrequent (some counties have not done a full reassessment in decades), keeping effective rates artificially low.</li></ol>`,
      },
      {
        heading: 'Rate is half the story — dollar amount matters too',
        html: `<p>A low rate on a high-value home produces a higher absolute bill than a high rate on a cheap home. Top 5 states by <strong>median annual property tax bill</strong>:</p><ol><li>New Jersey — about $9,200</li><li>New Hampshire — about $6,800</li><li>Connecticut — about $6,500</li><li>New York — about $6,300 (especially Long Island, Westchester)</li><li>Massachusetts — about $5,800</li></ol><p>Compare to bottom 5 by absolute bill:</p><ol><li>West Virginia — about $850</li><li>Alabama — about $700</li><li>Arkansas — about $900</li><li>Louisiana — about $950</li><li>Mississippi — about $1,000</li></ol><p>The Hawaii paradox: lowest effective rate, but a $1,900 median bill — higher than a dozen states with rates 3x higher, because Hawaii home values are so high.</p>`,
      },
      {
        heading: 'Three structural drivers',
        html: `<p>Why do rates differ so dramatically? Three main reasons:</p><ol><li><strong>School funding model.</strong> States that fund K–12 schools primarily through local property tax (NJ, IL, TX, NH) have high rates. States that use state income tax or sales tax to fund education (CA partially, HI fully) keep property tax low.</li><li><strong>Assessment caps and freezes.</strong> California (Prop 13), Florida (Save Our Homes), and Oregon all cap annual assessment increases, which lowers effective rates over time as market values outpace assessed values.</li><li><strong>Other tax revenue.</strong> States without income tax (TX, FL, NV, NH, TN, WY, SD, AK, WA) rely more on property and sales tax. Texas leans hard on property; Nevada leans on tourism and sales.</li></ol>`,
      },
      {
        heading: 'How to use this for a relocation decision',
        html: `<p>If you are deciding between two states, do not stop at property tax. Calculate <strong>total tax burden</strong> by adding:</p><ul><li>State income tax on your expected income</li><li>State and local sales tax × your typical spending</li><li>Property tax on your target home value</li><li>Vehicle registration and fees</li></ul><p>Texas-vs-California is a famous example: Texas has high property tax but no income tax. For a $400,000 home and $150,000 income, total tax burden in California is roughly $14,000 (low property + high income). In Texas it is roughly $9,500 (high property, no income). For higher incomes the gap widens further.</p><p>Use our state pages to look up current rates for any state, and our <a href="/compare/">compare tool</a> to put two states side by side.</p>`,
      },
    ],
    faqs: [
      { question: 'Which state has the highest property tax rate?', answer: 'New Jersey, with an effective rate of about 2.4 percent on market value, followed by Illinois at about 2.1 percent. Both produce median bills above $7,000 per year on typical homes.' },
      { question: 'Which state has the lowest property tax rate?', answer: 'Hawaii, at about 0.27 percent effective. However, Hawaii has the highest median home value in the country, so the absolute dollar bill is still around $1,900 — higher than several states with much higher rates.' },
      { question: 'Are no-income-tax states cheaper overall?', answer: 'Sometimes, but not always. Texas and New Hampshire have no income tax but among the highest property tax rates in the country. Florida and Tennessee have low or no income tax and moderate property tax. Always calculate total tax burden, not single tax categories.' },
      { question: 'Do property taxes go down when home values fall?', answer: 'Often more slowly than you would expect. Local governments adjust millage rates to maintain revenue when assessed values fall, which can offset some or all of the rate decrease. In states with assessment caps (CA, FL), there is little flexibility because assessed values were already below market.' },
      { question: 'How often do states reassess property values?', answer: 'Varies enormously. Texas and California use annual or transactional reassessments. Pennsylvania has counties that have not done a full reassessment in decades. Delaware has counties on a 50+ year cycle. Less frequent reassessment usually benefits long-time owners and disadvantages recent buyers.' },
      { question: 'Why is Cook County (Chicago) so expensive?', answer: 'Chicago Public Schools and the Cook County pension system both rely heavily on property tax. Decades of pension underfunding have shifted obligations onto current property owners. Effective rates in Cook County exceed 2.5 percent in many neighborhoods.' },
    ],
  },
  {
    slug: 'property-tax-exemptions-most-homeowners-miss',
    title: 'Property Tax Exemptions Most Homeowners Miss',
    description: 'Homestead, senior, veteran, disability, widow, agricultural, and solar exemptions — who qualifies, how to file, and how much they actually save. State-by-state guide.',
    category: 'Saving Strategies',
    updatedAt: u,
    intro: `<p>The single fastest way to lower your property tax bill is not to appeal the assessment — it is to claim every exemption you are entitled to. Yet a large share of qualifying homeowners never apply, either because they do not know an exemption exists or because the form looks bureaucratic. This guide covers the seven exemptions that can move the needle most: homestead, senior, veteran, disability, widow, agricultural, and renewable energy. For each, we explain who qualifies, the typical savings, and where the rules differ across states.</p>`,
    sections: [
      {
        heading: 'Homestead exemption (the most common)',
        html: `<p>Almost every state offers a homestead exemption that reduces the taxable value of your primary residence. The exemption is usually a flat dollar amount subtracted from assessed value:</p><ul><li><strong>Florida:</strong> first $50,000 of assessed value exempt for primary residence (with the second $25,000 exempt from non-school taxes).</li><li><strong>Texas:</strong> $100,000 exemption for school district taxes (passed in 2023, indexed for future increases).</li><li><strong>Louisiana:</strong> $75,000 exemption — among the highest, fully exempts many lower-priced homes from state property tax.</li><li><strong>Georgia:</strong> $2,000 statewide standard exemption with additional county-level exemptions.</li><li><strong>Mississippi:</strong> $7,500 standard plus generous additional senior/disabled exemptions.</li></ul><p>You usually must apply once after closing on your home — it is not automatic. Deadlines vary by state, often March 1 or April 1 for the current tax year. Missing the deadline means waiting until the following year. We list current homestead deadlines on our state pages.</p>`,
      },
      {
        heading: 'Senior exemption (age 65+)',
        html: `<p>Most states offer a senior or "elderly" exemption on top of the standard homestead. Eligibility usually starts at age 65, sometimes 62 or 60, and may be income-limited:</p><ul><li><strong>New York STAR (Enhanced):</strong> for homeowners 65+ with income under $98,700 (2024 limit), exempts the first $77,700 of assessed value from school taxes.</li><li><strong>Texas:</strong> additional $10,000 school district exemption for homeowners 65+, plus a tax ceiling that freezes school taxes at the level you paid the year you turned 65.</li><li><strong>Florida:</strong> additional $50,000 exemption for homeowners 65+ in many counties, income-limited.</li><li><strong>Cook County, IL:</strong> Senior Citizen Exemption reduces assessed value, plus a separate Senior Freeze for income-limited seniors.</li><li><strong>Pennsylvania:</strong> Property Tax/Rent Rebate program for seniors and people with disabilities under income limits.</li></ul><p>The Texas and Cook County "freeze" mechanisms are particularly valuable: once you qualify, your tax bill cannot rise even if assessed values do. Over 10 to 20 years, this can save tens of thousands of dollars.</p>`,
      },
      {
        heading: 'Veteran and disability exemptions',
        html: `<p>Veterans, especially disabled veterans, get some of the most generous exemptions in the country:</p><ul><li><strong>Texas:</strong> 100 percent disabled veterans pay zero property tax on their primary residence — full exemption.</li><li><strong>Florida:</strong> 100 percent disabled veterans get full exemption; partial disability gets a sliding-scale exemption based on disability percentage.</li><li><strong>New Jersey:</strong> 100 percent disabled veterans get full exemption.</li><li><strong>California:</strong> Disabled Veterans' Exemption up to $241,627 (2024), or $362,440 if income-limited.</li><li><strong>Most other states:</strong> partial exemptions based on VA disability rating, often $5,000 to $50,000 off assessed value.</li></ul><p>You typically need a VA disability rating letter and must file with your county assessor. The 100 percent disabled veteran exemption in Texas and Florida is one of the most valuable tax benefits in the entire US tax code — it can save $5,000 to $15,000 per year indefinitely.</p>`,
      },
      {
        heading: 'Widow, widower, and surviving spouse exemptions',
        html: `<p>Many states have a small but easy-to-claim exemption for widows and widowers:</p><ul><li><strong>Florida:</strong> $5,000 widow exemption on top of homestead.</li><li><strong>Mississippi:</strong> $7,500 additional for widows and widowers.</li><li><strong>Michigan:</strong> Disabled Veterans Survivors Exemption — full exemption for surviving spouses of 100% disabled veterans, indefinitely (until remarriage).</li></ul><p>These exemptions are usually overlooked because they are not large enough to be advertised, but they are easy to file (one form, typically requiring a death certificate) and there is no income limit in most states.</p>`,
      },
      {
        heading: 'Agricultural and conservation exemptions',
        html: `<p>If you own rural land used for agriculture, the savings can be enormous. Agricultural exemptions assess land at its agricultural use value rather than market value, often reducing the taxable value by 80–95 percent:</p><ul><li><strong>Texas:</strong> "Ag exemption" reduces taxable value to roughly $200 per acre regardless of market value — a 5-acre rural property with $100,000 market value can be assessed at $1,000.</li><li><strong>Florida:</strong> Greenbelt classification for agricultural land.</li><li><strong>California:</strong> Williamson Act contracts assess at agricultural value in exchange for a 10-year commitment.</li></ul><p>You generally need to demonstrate active agricultural use (specific minimum acreage, livestock counts, or crop revenue). Hobby farms and idle land usually do not qualify. The 5-year clawback rule in many states means converting ag-exempt land to residential triggers back taxes.</p>`,
      },
      {
        heading: 'Solar and renewable energy exemptions',
        html: `<p>Many states exempt the value added by solar panels, geothermal systems, and other renewable installations from property tax:</p><ul><li><strong>California:</strong> active solar excluded from assessed value.</li><li><strong>Texas:</strong> 100 percent of added value from solar exempt.</li><li><strong>New York:</strong> 15-year exemption on the added value of qualifying solar installations.</li><li><strong>Arizona, Massachusetts, Nevada, and others:</strong> similar full or partial exemptions.</li></ul><p>Without this exemption, adding $20,000 to $40,000 in solar would normally raise your assessed value and tax bill. The exemption preserves the financial case for solar installation. Check with your state energy office for the current exemption rules — they change with state incentive programs.</p>`,
      },
      {
        heading: 'How to claim what you are owed',
        html: `<p>Three steps to make sure you are not overpaying:</p><ol><li><strong>Pull your current property record card</strong> from the county assessor (often online). Check whether homestead and any other exemptions are listed.</li><li><strong>Check the eligibility list for your state.</strong> Most county assessor websites have a "exemptions" page with all available exemptions for that jurisdiction.</li><li><strong>File missing exemptions before the deadline.</strong> Most exemptions are not retroactive — you can only claim them going forward. Missing a year is missing a year of savings.</li></ol><p>The total annual savings from claiming every exemption you qualify for typically range from $200 to $5,000 depending on your state and personal situation. For disabled veterans in Texas or Florida, the savings can exceed $10,000 per year.</p>`,
      },
    ],
    faqs: [
      { question: 'Are property tax exemptions automatic?', answer: 'No. You almost always have to apply, usually once, and your jurisdiction will continue the exemption in subsequent years as long as the qualifying conditions remain. Missing the initial application is the single most common reason qualifying homeowners overpay.' },
      { question: 'Can I claim a homestead exemption on a second home?', answer: 'No. Homestead exemptions apply only to your primary residence — the home where you live more than half the year and where you are registered to vote. Some states (Florida, Texas) actively audit residency claims and impose penalties for false claims.' },
      { question: 'What is the difference between an exemption and a credit?', answer: 'An exemption reduces the taxable value of your home before the rate is applied. A credit is a dollar-for-dollar reduction of the final tax bill. Both lower what you owe, but credits are generally more valuable per dollar because they apply after the rate calculation.' },
      { question: 'Do exemptions transfer when I move?', answer: 'Sometimes. Florida and California allow homestead and Save Our Homes / Prop 13 portability for moves within the state under specific conditions. Most other states require a new application for each property. Always check before moving — losing portability can cost thousands per year.' },
      { question: 'Can I appeal a denied exemption?', answer: 'Yes. Most county assessors have a formal appeal process for denied exemptions, usually with a 30 to 60 day window after the denial notice. Common denial reasons include incomplete documentation or missed deadlines, both of which can usually be fixed on appeal.' },
      { question: 'Is the homestead exemption the same as the homestead protection in bankruptcy?', answer: 'No. Property tax homestead exemption reduces your tax bill. Bankruptcy homestead protection prevents creditors from forcing the sale of your primary residence. Different laws, different protections, often confused because they share a name.' },
    ],
  },
  {
    slug: 'why-property-taxes-vary-10x',
    title: 'Why Property Taxes Vary 10x Between Neighbors (Even on Identical Homes)',
    description: 'How Proposition 13, purchase-price resets, grandfathered assessments, and reassessment frequency create huge property tax gaps between identical homes on the same street.',
    category: 'Tax Mechanics',
    updatedAt: u,
    intro: `<p>Two identical homes on the same street can have property tax bills that differ by 10 times. This isn't a glitch or an error — it's the result of how different states handle assessment caps, purchase price resets, and reassessment frequency. Understanding these mechanics is essential for anyone buying a home, because the tax bill you inherit from the previous owner is often nothing like the one you'll actually pay starting next year.</p>`,
    sections: [
      {
        heading: 'California Proposition 13: the original assessment freeze',
        html: `<p>Proposition 13, passed by California voters in 1978, is the most consequential property tax law in modern US history. It works in three steps:</p><ol><li>Property is assessed at market value when purchased.</li><li>That assessed value can rise by no more than 2 percent per year, regardless of actual market appreciation.</li><li>The base property tax rate is capped at 1 percent of assessed value, plus voter-approved local levies.</li></ol><p>The result: a home bought in 1985 for $200,000 has an assessed value today of about $360,000 (after 40 years of capped 2 percent growth), while the identical home next door bought last year for $1,500,000 is assessed at $1,500,000. The 1985 owner pays about $3,600 per year. The 2024 buyer pays about $15,000. Same home, same street, 4x difference.</p><p>This explains California's famous tax disparity: long-term owners pay almost nothing while recent buyers pay full market rates. The system creates massive incentives to never sell (because the next home will be reassessed) and locks older homeowners in place.</p>`,
      },
      {
        heading: 'Texas: opposite extreme, annual reassessment',
        html: `<p>Texas does the exact opposite. Counties reassess every property every year at full market value. There is no cap on annual increases for non-homesteaded property. For homesteaded property, increases are capped at 10 percent per year (plus the value of new improvements), which can still be brutal in fast-rising markets.</p><p>The result: in cities like Austin, where home values rose 40 to 60 percent in a single year (2021–2022), property tax bills also rose by the maximum 10 percent annually for several years in a row. Long-time owners and new buyers pay similar amounts because everyone is reassessed annually.</p><p>Texas has the appeal mechanism precisely because rapid reassessment generates so many disputes. Roughly 30 to 50 percent of Texas homeowners file at least one property tax appeal in their ownership tenure.</p>`,
      },
      {
        heading: 'Florida Save Our Homes: a hybrid model',
        html: `<p>Florida's "Save Our Homes" amendment caps annual assessed value increases at 3 percent or the inflation rate (whichever is lower) for homesteaded properties only. Unlike California, the cap resets when the home is sold — the new owner is reassessed at current market value, then their cap clock starts.</p><p>The result is similar to California (long-term owners pay much less than recent buyers) but slightly more flexible. Florida also added "portability" in 2008 — when you sell your homesteaded primary residence and buy another in Florida, you can transfer up to $500,000 of your accumulated savings to the new home's assessed value.</p><p>For non-homesteaded property (rentals, second homes, commercial), the cap is 10 percent — much closer to Texas-style annual reassessment.</p>`,
      },
      {
        heading: 'Counties that have not reassessed in decades',
        html: `<p>Some counties go to the opposite extreme — no reassessment for years or even decades. Pennsylvania is famous for this. Allegheny County (Pittsburgh) used a 2002 base year for many years. Other Pennsylvania counties used assessments from the 1960s and 1970s, periodically updated by an "equalization ratio."</p><p>The result: property tax bills bear almost no relationship to current market value. A home that has tripled in value since the last reassessment pays the same property tax as before. New construction is assessed at the old base year's price levels. The "common level ratio" is used to convert old assessed values into estimated market values for sale and appeal purposes — see our <a href="/guide/effective-vs-nominal-property-tax-rates/">effective vs nominal guide</a> for more on this.</p><p>Pennsylvania began modernizing in the 2010s, but several counties still operate with multi-decade-old assessments.</p>`,
      },
      {
        heading: 'When you buy: prepare for the post-purchase reassessment',
        html: `<p>The most expensive property tax surprise for buyers happens when they look at the seller's tax bill, assume that's their new tax bill, and discover next year that the home was reassessed at the purchase price. Common in:</p><ul><li><strong>California:</strong> immediate reassessment to purchase price under Prop 13. The seller's $3,000/year bill becomes your $15,000/year bill.</li><li><strong>Florida (non-homesteaded transition):</strong> Save Our Homes cap is wiped when you buy, even if you immediately homestead the property.</li><li><strong>Massachusetts:</strong> reassessment within one year of sale.</li><li><strong>Texas:</strong> annual reassessment captures purchase price quickly.</li></ul><p>Always look up the <strong>current millage rate × likely new assessed value</strong> when budgeting, not the seller's existing bill. Our <a href="/calculator/">calculator</a> uses current rates and lets you input the purchase price as the new assessment to estimate your real bill.</p>`,
      },
      {
        heading: 'The fairness debate',
        html: `<p>Each system creates winners and losers:</p><ul><li><strong>California / Florida (assessment caps):</strong> reward long-term owners, punish new buyers, restrict housing mobility, lock seniors in homes too large for them.</li><li><strong>Texas (annual reassessment):</strong> spreads burden across all owners, but creates volatile bills tied to market swings, frustrating retirees on fixed incomes.</li><li><strong>Pennsylvania (infrequent reassessment):</strong> fossilizes the tax base, distorts incentives, and produces wildly different effective rates between similar properties.</li></ul><p>There is no objectively correct system — each reflects a political compromise between revenue stability, fairness across owners, and protection for incumbents. Which system you live under affects your home buying math more than most other factors.</p>`,
      },
    ],
    faqs: [
      { question: 'Will my property tax go up when I buy a home?', answer: 'In most states, yes — the home will be reassessed at your purchase price, and your tax bill will reflect current market value. In California and Florida, this reset can multiply the seller\'s bill several times. Always estimate the post-reassessment bill, not the seller\'s current bill, before buying.' },
      { question: 'How does Proposition 13 work in California?', answer: 'Property is assessed at market value when purchased, then assessed value can rise by at most 2 percent per year regardless of actual appreciation. The tax rate is capped at 1 percent plus voter-approved levies. Long-term owners pay far less than recent buyers on identical homes.' },
      { question: 'Do property taxes ever decrease?', answer: 'Yes, but rarely. Assessed values can drop after reassessment in a falling market, but local governments often increase millage rates to maintain revenue, offsetting the decrease. Successful appeals can reduce your bill, and qualifying for new exemptions (especially senior exemptions) can drop it substantially.' },
      { question: 'What happens to property tax when you inherit a home?', answer: 'Varies by state. In California, parent-child transfers used to preserve the Prop 13 base value, but Prop 19 (2021) significantly limited this. In most other states, inheritance does not trigger reassessment as long as the new owner lives in the property; but check your state for "transfer tax" rules separately.' },
      { question: 'Can I appeal my assessment if it is much higher than my neighbor\'s?', answer: 'Sometimes. The basis for appeal is usually market value, not your neighbor\'s assessment. If you can show that comparable recent sales support a lower value, you have a case. Pointing at a neighbor\'s lower assessed value alone is rarely successful — assessment freezes and exemptions are legal reasons for differences.' },
      { question: 'Does paying off my mortgage affect property tax?', answer: 'No. Property tax is based on assessed value and millage, not mortgage status. However, when your mortgage is paid off, your bank no longer escrows property tax — you pay the county directly. Many homeowners are surprised at the size of the bill when it stops being included in the monthly mortgage payment.' },
    ],
  },
  {
    slug: 'true-cost-of-owning-a-home',
    title: 'The True Cost of Owning a Home: Beyond Property Tax',
    description: 'Property tax + insurance + HOA + maintenance + utilities — the five categories that make total ownership cost 30 to 50 percent higher than the mortgage payment alone. State-by-state breakdown.',
    category: 'Ownership Cost',
    updatedAt: u,
    intro: `<p>Most home buyers focus on the mortgage payment and assume the rest is rounding error. It is not. The annual cost of owning a home — property tax, insurance, HOA fees, maintenance, and utilities — adds 30 to 50 percent on top of the principal and interest payment, and varies more across states than the mortgage itself. This guide breaks down each category, shows where the differences come from, and gives you a realistic budgeting framework so the costs do not blindside you.</p>`,
    sections: [
      {
        heading: 'Property tax: the biggest variable',
        html: `<p>Property tax is the largest after-mortgage cost in most states and varies more than any other component. A $400,000 home costs roughly:</p><ul><li>$9,000+ annually in New Jersey</li><li>$7,500 in Illinois</li><li>$7,000 in Texas</li><li>$3,500 in Florida</li><li>$2,500 in Hawaii (low rate, high value)</li><li>$1,200 in Alabama</li></ul><p>For a 30-year mortgage at current rates on the same $400,000 home, monthly principal and interest is roughly $2,500. The Texas owner adds $580/month for property tax — a 23 percent increase to the monthly cost. The Alabama owner adds $100/month — a 4 percent increase. Same home, completely different cost of ownership.</p><p>See our <a href="/guide/state-by-state-property-tax-burden/">state-by-state property tax burden guide</a> for the full ranking, and our <a href="/calculator/">calculator</a> for your specific situation.</p>`,
      },
      {
        heading: 'Homeowners insurance: rising fast in many states',
        html: `<p>Average annual homeowners insurance premiums have risen 30 percent or more over the past five years, driven primarily by climate-related claims (wildfires, hurricanes, hail). Current estimates by state:</p><ul><li><strong>Florida:</strong> highest in the nation, often $6,000 to $10,000 per year on a $400,000 home in coastal zones. Some insurers have stopped writing new policies entirely; the state-run Citizens Property Insurance has become the largest insurer.</li><li><strong>Louisiana:</strong> $4,000 to $7,000, with ongoing market disruption from Hurricane Ida.</li><li><strong>Texas:</strong> $3,500 to $5,500, especially in hail-prone DFW and coastal areas.</li><li><strong>Oklahoma:</strong> $4,500+ due to severe storm exposure.</li><li><strong>California:</strong> $1,500 to $4,500, but many insurers have withdrawn from wildfire-prone zones, forcing buyers into the FAIR Plan (last-resort coverage).</li><li><strong>Low-cost states (NH, VT, OR, WA, ID):</strong> $700 to $1,500 — among the cheapest in the country.</li></ul><p>If you are buying in a coastal, wildfire, or tornado-prone area, get quotes <em>before</em> you make an offer. In the most affected zones, insurance has gone from a minor cost to a deal-breaker.</p>`,
      },
      {
        heading: 'HOA fees: the wildcard',
        html: `<p>If your property is in a homeowners association, condominium, or planned community, monthly HOA fees can rival the mortgage payment in extreme cases. Typical ranges:</p><ul><li><strong>Single-family suburban HOAs:</strong> $25 to $150/month for common areas, landscaping.</li><li><strong>Townhouse / planned communities:</strong> $150 to $400/month.</li><li><strong>Mid-rise condos:</strong> $400 to $1,000/month, covering building maintenance, insurance, and reserves.</li><li><strong>Luxury or amenity-heavy condos:</strong> $1,000 to $3,000+/month.</li></ul><p>HOA fees also tend to rise faster than inflation, especially after special assessments (one-time charges for major repairs). Florida condos in particular have seen massive special assessments in 2024 and 2025 following the 2021 Surfside collapse and subsequent inspection requirements — some buildings have hit owners with $100,000+ per unit assessments.</p><p>Always read the HOA financials before buying. Look for: reserve fund balance (should cover at least 70 percent of expected major repairs), recent special assessments, monthly fee history (steep year-over-year increases are a warning), and pending litigation.</p>`,
      },
      {
        heading: 'Maintenance: the 1 percent rule',
        html: `<p>Real estate investors use the "1 percent rule" for budgeting: expect to spend approximately 1 percent of your home's value per year on maintenance and repairs, averaged over a 10 to 20 year ownership period. For a $400,000 home, that is $4,000 per year, or about $330 per month.</p><p>Maintenance is uneven — you might spend $0 some years and $15,000 in a roof-replacement year. The 1 percent average is a useful budget anchor but should be backed up by an actual reserve fund. Items to plan for:</p><ul><li><strong>Roof:</strong> $8,000 to $20,000 every 20 to 25 years</li><li><strong>HVAC:</strong> $5,000 to $12,000 every 15 to 20 years</li><li><strong>Water heater:</strong> $1,200 to $3,500 every 10 to 15 years</li><li><strong>Exterior paint:</strong> $3,000 to $8,000 every 7 to 10 years</li><li><strong>Driveway, deck, fencing:</strong> $2,000 to $10,000 every 15 to 25 years</li></ul><p>Older homes (50+ years) and homes in harsh climates trend toward 1.5 to 2 percent. New homes in mild climates can run closer to 0.5 percent for the first 10 years, then jump as systems age.</p>`,
      },
      {
        heading: 'Utilities: the easiest to overlook',
        html: `<p>Average monthly utility costs (electric + gas + water + sewer) for a 2,000 sq ft single-family home:</p><ul><li><strong>Northeast (NY, MA, CT, NJ):</strong> $350 to $500 — high heating costs in winter, increasingly high cooling in summer.</li><li><strong>Texas, Arizona, Florida:</strong> $300 to $450 — summer cooling dominates.</li><li><strong>California:</strong> $250 to $400 with mild climate but high per-kWh rates.</li><li><strong>Midwest:</strong> $200 to $350 — moderate climate, low rates.</li><li><strong>Pacific Northwest:</strong> $150 to $250 — cheapest in the country thanks to hydroelectric power.</li></ul><p>Utility costs depend more on home size and insulation than on geography alone. A 4,000 sq ft poorly-insulated house in Phoenix can run $600+ per month in summer. A new-build with modern insulation can match a 2,000 sq ft home half the size.</p>`,
      },
      {
        heading: 'A realistic budget worksheet',
        html: `<p>For a $400,000 home, here is a typical "fully loaded" monthly cost compared to mortgage alone:</p><ul><li>Principal + interest (30 yr at 7%): <strong>$2,500</strong></li><li>Property tax (TX example): <strong>$580</strong></li><li>Insurance: <strong>$300</strong></li><li>HOA (suburban single-family): <strong>$50</strong></li><li>Maintenance (1% rule averaged): <strong>$330</strong></li><li>Utilities: <strong>$300</strong></li></ul><p><strong>Total: $4,060/month</strong> versus the mortgage payment of $2,500. The non-mortgage costs add $1,560 per month — 62 percent on top of the principal and interest.</p><p>This is why "I can afford the mortgage payment" is the wrong frame for affordability. Use 28/36 ratios on the <em>fully loaded</em> cost, not the mortgage alone. If your gross monthly income is $10,000, you can comfortably afford about $2,800 in housing costs (28 percent), which means a target fully loaded cost of $2,800 — translating to a much smaller mortgage than the back-of-envelope mortgage calculator suggests.</p>`,
      },
    ],
    faqs: [
      { question: 'How much should I budget for non-mortgage costs?', answer: 'Plan for 1.5 to 2 percent of the home\'s value per year for property tax (varies by state), 0.5 to 1.5 percent for insurance, 1 percent for maintenance, plus actual HOA and utility costs. Total: typically 30 to 50 percent on top of the mortgage payment.' },
      { question: 'Is the 1 percent maintenance rule still accurate?', answer: 'It is still a reasonable starting point for newer homes in mild climates, but rises to 1.5 to 2 percent for older homes or those in harsh climates. The rule is an average over 15+ years, not a yearly amount — you will have $0 years and $15,000 years.' },
      { question: 'Why has homeowners insurance gone up so fast?', answer: 'Climate-related claims (hurricanes, wildfires, hail, flooding) have grown faster than premiums, forcing insurers to either raise rates aggressively or exit markets. Florida, California, and Louisiana have seen the most disruption, with several major insurers withdrawing entirely.' },
      { question: 'Are HOA fees tax deductible?', answer: 'Generally no for primary residences. They are deductible for rental properties as a business expense. Some special assessments for capital improvements may be added to your cost basis for capital gains tax purposes when you sell.' },
      { question: 'Can I deduct property taxes from federal income tax?', answer: 'Yes, but the State and Local Tax (SALT) deduction is capped at $10,000 total since 2018. For high-tax states like New Jersey and Illinois, this cap means most homeowners cannot deduct their full property tax bill.' },
      { question: 'Does paying off my mortgage actually save money?', answer: 'Yes — you eliminate the principal and interest payment. But all other costs (tax, insurance, maintenance, utilities) continue. A "paid off" home in a high-tax state like New Jersey can still cost $1,500 to $2,000 per month to own. Plan for ongoing costs in retirement, not just the mortgage.' },
    ],
  },
];

export function getAllGuides(): Guide[] {
  return guides;
}

export function getGuideBySlug(slug: string): Guide | undefined {
  return guides.find((g) => g.slug === slug);
}
