/**
 * State-level property tax exemption data.
 * Covers homestead, senior/over-65, disabled veteran, and disability exemptions.
 *
 * Sources: State Department of Revenue / Taxation websites, Tax Foundation,
 * National Association of Counties. Vintage: 2026-04-21.
 *
 * Note: County-level additions apply in many states. This file reflects the
 * STATUTORY STATE-LEVEL baseline. Actual property tax savings vary by county.
 */

export interface StateExemptionData {
  /** State slug matching propertytaxpeek db (e.g. 'california') */
  slug: string;
  /** Is there a meaningful homestead exemption? */
  hasHomestead: boolean;
  /** Base homestead exemption value (dollars of assessed value) */
  homesteadBase: number;
  /** Homestead description (percentage / special rule / auto-apply / must-file) */
  homesteadDescription: string;
  /** Senior / over-65 exemption (additional to homestead) */
  seniorExemption: string | null;
  /** Disabled veteran exemption */
  veteranExemption: string | null;
  /** Disability (non-veteran) exemption */
  disabilityExemption: string | null;
  /** Assessment limit / cap (e.g. "3%/year Prop 13 in CA") */
  assessmentCap: string | null;
  /** How to file - simplified step or form name */
  filingProcess: string;
  /** Key note about this state's exemption system */
  notes: string;
}

export const stateExemptionData: StateExemptionData[] = [
  { slug: 'alabama', hasHomestead: true, homesteadBase: 4000,
    homesteadDescription: 'Alabama offers a $4,000 state homestead exemption on assessed value (applied to primary residence). Counties may add local amounts.',
    seniorExemption: 'Full state property tax exemption for residents 65+ with adjusted gross income under $12,000 (plus full county exemption if AGI < $12K).',
    veteranExemption: 'Disabled veterans (100% service-connected) exempt from all state + county property taxes on homestead.',
    disabilityExemption: 'Total and permanent disability: full exemption similar to senior rules.',
    assessmentCap: null, filingProcess: 'File Form PT-50H with county revenue commissioner.',
    notes: 'Alabama has the lowest median property tax in the US. Generous senior/veteran exemptions.' },

  { slug: 'alaska', hasHomestead: true, homesteadBase: 150000,
    homesteadDescription: 'Alaska mandates $150,000 residential homestead exemption for senior citizens 65+ and disabled veterans. No general homestead for all homeowners.',
    seniorExemption: '$150,000 off assessed value for residents 65+. Applied automatically once application filed.',
    veteranExemption: '$150,000 exemption for disabled veterans rated 50%+ service-connected.',
    disabilityExemption: 'Widows/widowers of qualifying seniors/veterans retain exemption.',
    assessmentCap: null, filingProcess: 'File with local borough assessor by March 31.',
    notes: 'Alaska has no state property tax — all property tax is local. State-mandated senior/veteran exemption applied by borough.' },

  { slug: 'arizona', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'Arizona does not have a general homestead property tax exemption, but offers $4,748 personal property exemption (2025 inflation-adjusted) and income-based relief for seniors.',
    seniorExemption: 'Senior Property Valuation Protection: freezes home value for seniors 65+ with income under $43,733 (single, 2025).',
    veteranExemption: 'Disabled veterans exemption up to $4,748 on assessed value (2025).',
    disabilityExemption: 'Widows, widowers, or totally/permanently disabled residents: $4,748 exemption.',
    assessmentCap: '5% annual LPV (Limited Property Value) cap applies to most residential parcels.',
    filingProcess: 'Apply through county assessor (Form DOR 82514 for senior freeze).',
    notes: 'Arizona uses Limited Property Value (LPV) system. Senior valuation freeze is most valuable benefit — locks assessed value in place.' },

  { slug: 'arkansas', hasHomestead: true, homesteadBase: 425,
    homesteadDescription: 'Arkansas Homestead Property Tax Credit: up to $425/year credit against property tax (applied automatically to primary residence).',
    seniorExemption: 'Assessment freeze for homeowners 65+ or disabled — assessed value locked in at age 65.',
    veteranExemption: 'Disabled veterans (100% service-connected): full property tax exemption on homestead.',
    disabilityExemption: 'Total disability: assessment freeze same as seniors.',
    assessmentCap: '5% annual cap on assessed value increases (10% for non-homestead).',
    filingProcess: 'Homestead credit auto-applied when Form AR-PT-1 filed with county assessor.',
    notes: 'Homestead is a tax CREDIT ($425 max), not valuation exemption. Senior freeze is very valuable over time.' },

  { slug: 'california', hasHomestead: true, homesteadBase: 7000,
    homesteadDescription: 'California homeowner exemption: $7,000 off assessed value for primary residence. Saves about $70/year at 1% tax rate.',
    seniorExemption: 'Prop 19 (2020): seniors 55+ can transfer property tax basis to new home (up to 3 times statewide).',
    veteranExemption: 'Disabled veterans: up to $161,083 basic exemption (2025), increased to $241,627 if low-income. 100% disabled.',
    disabilityExemption: 'Totally disabled veterans: matches disabled veteran rates.',
    assessmentCap: 'Prop 13: assessed value can only increase max 2%/year. Reset only upon sale (or Prop 19 transfer).',
    filingProcess: 'File Form BOE-266 homeowner claim with county assessor.',
    notes: 'Prop 13 (1978) is California\'s defining feature — long-term homeowners pay dramatically less than recent buyers. Homeowner $7K exemption is small but compounds over decades.' },

  { slug: 'colorado', hasHomestead: true, homesteadBase: 200000,
    homesteadDescription: 'Colorado Senior Homestead Exemption: 50% of first $200,000 of home value exempt (max $100,000 reduction) for seniors 65+ who have lived in home 10+ years.',
    seniorExemption: 'Same 50%/$200K formula for seniors 65+ (10-year residency required).',
    veteranExemption: '50% of first $200,000 exempt for 100% disabled veterans (no residency requirement).',
    disabilityExemption: 'Surviving spouses of qualifying veterans/seniors retain exemption.',
    assessmentCap: null, filingProcess: 'File Form with county assessor by July 15 (for exemption year).',
    notes: 'Colorado senior/veteran benefit suspended in lean state budget years — funded in 2025 but has been paused periodically.' },

  { slug: 'connecticut', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'Connecticut has no general homestead exemption. Relief comes through veteran exemption and state-funded Circuit Breaker program for elderly.',
    seniorExemption: 'Elderly & Disabled Homeowner Circuit Breaker: income-based credit up to $1,250 (single) / $1,500 (married) for ages 65+ with income under $43,800 single / $53,400 joint (2025).',
    veteranExemption: '$3,000 minimum veteran exemption (more for disabled ranging $10K-$19K).',
    disabilityExemption: 'Circuit Breaker also covers totally disabled under 65.',
    assessmentCap: null, filingProcess: 'File Form M-35H with local assessor by May 15.',
    notes: 'Connecticut has high property taxes and no general homestead — relief targeted at elderly/disabled via Circuit Breaker credits.' },

  { slug: 'delaware', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'Delaware has no general homestead exemption at state level. County exemptions apply (New Castle, Kent, Sussex).',
    seniorExemption: 'Senior School Property Tax Credit (state): up to $500 credit for seniors 65+ (must be DE resident 10+ years).',
    veteranExemption: 'Disabled Veterans Property Tax Credit: 100% disabled veterans get credit equal to school property tax portion.',
    disabilityExemption: 'Same senior credit for disabled under 65 in some counties.',
    assessmentCap: null, filingProcess: 'Apply for school tax credit via Delaware Division of Revenue.',
    notes: 'Delaware has very low property tax overall. State-level benefit is $500 school tax credit for seniors.' },

  { slug: 'district-of-columbia', hasHomestead: true, homesteadBase: 78700,
    homesteadDescription: 'DC Homestead Deduction: $78,700 off assessed value (adjusted annually for inflation). Reduces first-year property tax by ~$670 at 0.85% rate.',
    seniorExemption: 'Senior Citizen Property Tax Relief: 50% reduction in property tax for homeowners 65+ with household income under $142,800 (2025).',
    veteranExemption: 'Disabled veterans (100%): $500 additional credit.',
    disabilityExemption: 'Disability tax deferral programs available.',
    assessmentCap: '10% annual cap on taxable assessment for homesteaded residential property.',
    filingProcess: 'File homestead application with Office of Tax and Revenue (one-time).',
    notes: 'DC has one of the most generous homestead deductions ($78,700). Combined with 10% assessment cap protects long-term residents.' },

  { slug: 'florida', hasHomestead: true, homesteadBase: 50000,
    homesteadDescription: 'Florida Homestead Exemption: up to $50,000 off assessed value ($25K applies to all taxes, additional $25K applies to non-school taxes on value between $50K-$75K).',
    seniorExemption: 'Limited senior additional exemption up to $50,000 (county option, income-based). Portable to new home under Save Our Homes.',
    veteranExemption: 'Disabled veterans (100% service-connected): full property tax exemption.',
    disabilityExemption: 'Total and permanent disability: full exemption similar to veterans.',
    assessmentCap: 'Save Our Homes: 3% annual cap on assessed value increases for homesteaded property.',
    filingProcess: 'File Form DR-501 with county property appraiser by March 1.',
    notes: 'Florida homestead + Save Our Homes (3% cap) is one of the strongest homeowner protections in the US. Portability allows transferring accumulated savings to new FL home.' },

  { slug: 'georgia', hasHomestead: true, homesteadBase: 2000,
    homesteadDescription: 'Georgia Standard Homestead Exemption: $2,000 off assessed value for primary residence. Many counties add local exemptions.',
    seniorExemption: 'Floating homestead exemption for 65+ (tied to income). Many counties offer age-specific exemptions.',
    veteranExemption: 'Disabled veterans: $109,986 exemption (2025). Widow/widower of KIA: full exemption.',
    disabilityExemption: 'Disability exemption similar to senior amounts in most counties.',
    assessmentCap: null, filingProcess: 'File homestead application with county tax commissioner by April 1.',
    notes: 'Georgia state homestead is small ($2K). Real savings come from county-specific additional exemptions — check local options.' },

  { slug: 'hawaii', hasHomestead: true, homesteadBase: 100000,
    homesteadDescription: 'Hawaii home exemption varies by county: Honolulu $100K (age 65+ gets $140K), Maui $200K, Kauai $160K, Hawaii County $40K.',
    seniorExemption: 'Age-based increases in home exemption (e.g., Honolulu: $140K at 65, $180K at 75).',
    veteranExemption: 'Disabled veterans get additional county-specific exemptions (Honolulu: additional $50K).',
    disabilityExemption: 'Totally disabled: same as senior exemption in most counties.',
    assessmentCap: null, filingProcess: 'File with county real property assessment division by September 30.',
    notes: 'Hawaii exemptions are COUNTY-administered despite state statute. Amounts vary significantly between islands.' },

  { slug: 'idaho', hasHomestead: true, homesteadBase: 125000,
    homesteadDescription: 'Idaho Homeowner\'s Exemption: 50% of assessed home value up to $125,000 (2025). Applied automatically to primary residence.',
    seniorExemption: 'Property Tax Reduction ("Circuit Breaker"): up to $1,500 credit for seniors 65+/widow/widower/disabled with income under $37,810 (2025).',
    veteranExemption: 'Disabled veterans (100% service-connected): up to $1,500 credit (income limits waived).',
    disabilityExemption: 'Full coverage for totally disabled + blind individuals via Circuit Breaker.',
    assessmentCap: null, filingProcess: 'File Form 63 with county assessor (one-time for homeowner exemption).',
    notes: 'Idaho\'s 50%-of-value-up-to-$125K is one of the most valuable homeowner exemptions.' },

  { slug: 'illinois', hasHomestead: true, homesteadBase: 6000,
    homesteadDescription: 'Illinois General Homestead Exemption: $6,000 off assessed value ($10,000 in Cook County). Reduces taxable value for primary residence.',
    seniorExemption: 'Senior Homestead Exemption: additional $5,000 for 65+. Senior Assessment Freeze available with income limit ($65,000 in 2025).',
    veteranExemption: 'Disabled Veterans Exemption: $2,500-$5,000 based on disability %, or full exemption for 100% disabled.',
    disabilityExemption: 'Disabled Persons Exemption: $2,000. Returning Veterans: $5,000 for year of return.',
    assessmentCap: null, filingProcess: 'File with county Chief Assessor (Form PTAX-324 for homestead).',
    notes: 'Illinois has one of highest property tax rates in US. Multiple stackable exemptions (general + senior + assessment freeze) critical for seniors.' },

  { slug: 'indiana', hasHomestead: true, homesteadBase: 48000,
    homesteadDescription: 'Indiana Homestead Deduction: $48,000 or 60% of assessed value, whichever is lower. Plus Supplemental Homestead Deduction: 35% of remaining value up to $600K.',
    seniorExemption: 'Over-65 Deduction: $14,000 off assessed value (income under $30K single / $40K joint).',
    veteranExemption: 'Disabled veterans (totally disabled): $24,960 deduction plus age-based bonus.',
    disabilityExemption: 'Blind/Disabled Deduction: $12,480.',
    assessmentCap: 'Circuit Breaker: caps residential property tax at 1% of gross assessed value (2% for 2nd home, 3% for rental/business).',
    filingProcess: 'File with county auditor (Form HC10 for homestead, once per home).',
    notes: 'Indiana has one of best circuit breaker systems — 1% cap on primary homes combined with homestead/senior deductions.' },

  { slug: 'iowa', hasHomestead: true, homesteadBase: 4850,
    homesteadDescription: 'Iowa Homestead Tax Credit: reduces taxable value by $4,850. Plus Homestead Exemption for 65+ (new 2023): $3,250 off taxable value (expanded to $6,500 in 2024).',
    seniorExemption: 'Homestead Exemption for 65+: $6,500 off taxable value (in addition to Homestead Credit).',
    veteranExemption: 'Disabled Veterans Credit: full property tax exemption on homestead for 100% service-connected disability.',
    disabilityExemption: 'Family Farm Credit & Elderly/Disabled Property Tax Credit (income-based).',
    assessmentCap: null, filingProcess: 'File Form 54-028 with county assessor (one-time).',
    notes: 'Iowa expanded senior exemption significantly in 2023-2024 — $6,500 credit is new and valuable.' },

  { slug: 'kansas', hasHomestead: true, homesteadBase: 75000,
    homesteadDescription: 'Kansas Homestead Refund: up to $700 refund for homeowners meeting income limits ($37,750 in 2025). "SAFESR" refunds seniors 65+ ($22,300 income limit).',
    seniorExemption: 'SAFESR Refund: 75% property tax rebate for seniors 65+ under income limit.',
    veteranExemption: 'Disabled veterans (50%+): Homestead Refund increased, no income limit.',
    disabilityExemption: 'Totally disabled qualify for Homestead Refund regardless of age.',
    assessmentCap: null, filingProcess: 'File Kansas Form K-40H (Homestead) by April 15.',
    notes: 'Kansas refund is a REBATE check based on income and taxes paid — not a direct exemption. Apply annually.' },

  { slug: 'kentucky', hasHomestead: true, homesteadBase: 49100,
    homesteadDescription: 'Kentucky Homestead Exemption: $49,100 off assessed value (2025-2026, adjusted biennially) for homeowners 65+ OR disabled.',
    seniorExemption: '$49,100 exemption applied at age 65 (same as homestead).',
    veteranExemption: 'Disabled veterans qualify for $49,100 exemption regardless of age.',
    disabilityExemption: 'Totally disabled: same $49,100 exemption as seniors.',
    assessmentCap: null, filingProcess: 'File Form 62A350 with property valuation administrator (PVA).',
    notes: 'Kentucky has a SINGLE generous exemption ($49K) for 65+/disabled — no general homestead for under-65 non-disabled.' },

  { slug: 'louisiana', hasHomestead: true, homesteadBase: 75000,
    homesteadDescription: 'Louisiana Homestead Exemption: $75,000 off assessed value (equivalent to $7,500 off taxable value, since LA taxes 10% of market).',
    seniorExemption: 'Special Assessment Freeze for 65+ with income under $100,000 — locks assessed value in place.',
    veteranExemption: 'Disabled veterans (100%): doubles homestead exemption to $150,000 ($15K taxable value).',
    disabilityExemption: 'Totally disabled: similar treatment to seniors for freeze.',
    assessmentCap: 'Special Assessment freeze for seniors functions as effective cap.',
    filingProcess: 'File with parish assessor (one-time for homestead, annual renewal for senior freeze).',
    notes: 'Louisiana assessment at 10% of market + $75K exemption means most homes under $150K pay no state/parish property tax.' },

  { slug: 'maine', hasHomestead: true, homesteadBase: 25000,
    homesteadDescription: 'Maine Homestead Exemption: $25,000 off assessed value. Applied as $25K just-value deduction for primary residence of 12+ months.',
    seniorExemption: 'Property Tax Stabilization (LD 290, suspended 2023): was assessment freeze at 65. Currently Property Tax Fairness Credit: up to $2,000 refundable credit.',
    veteranExemption: 'Veteran Property Tax Exemption: $6,000 for all veterans, $50,000 for paraplegic/100%-disabled.',
    disabilityExemption: 'Blind Exemption: $4,000 off just value.',
    assessmentCap: null, filingProcess: 'File Homestead Application with municipal assessor.',
    notes: 'Maine temporarily had excellent senior freeze (LD 290) but suspended 2023. Property Tax Fairness Credit is current alternative.' },

  { slug: 'maryland', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'Maryland Homestead Tax Credit: caps taxable assessment increases at 10%/year (state level). County caps vary: Baltimore City 4%, Montgomery County 10%.',
    seniorExemption: 'Senior Tax Credit: up to $1,000 credit for 65+ with household income under $94,600 (2025).',
    veteranExemption: 'Disabled veterans (100%): full property tax exemption on homestead.',
    disabilityExemption: 'Blind Persons exemption: $15,000 off assessed value.',
    assessmentCap: 'Homestead Tax Credit caps assessment increases at 10% state, with lower county caps.',
    filingProcess: 'Apply once with Maryland Department of Assessments (SDAT Form).',
    notes: 'Maryland has no dollar exemption but assessment cap (10% state, lower in some counties) provides strong long-term protection.' },

  { slug: 'massachusetts', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'Massachusetts has no property tax homestead exemption (different from creditor-protection homestead). Personal property tax exemptions exist.',
    seniorExemption: 'Clause 41C: $1,000 minimum exemption for 65+ with income limits. Circuit Breaker Credit up to $2,590 (2025).',
    veteranExemption: 'Clause 22: $400-$1,500 based on disability %, surviving spouses covered. 100% disabled: full exemption on home.',
    disabilityExemption: 'Clause 37: $500 minimum for blind. Circuit Breaker for disabled under 65.',
    assessmentCap: 'Proposition 2½: total municipal property tax levy cannot grow more than 2.5% annually (aggregate cap).',
    filingProcess: 'Apply with local Board of Assessors (annual renewal for Clause 41/22).',
    notes: 'Prop 2½ is MA\'s defining feature — limits total tax growth per municipality, not individual homes. No broad homestead exemption.' },

  { slug: 'michigan', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'Michigan Principal Residence Exemption (PRE): exempts primary residence from 18 mills of school operating tax (saves ~$1,800/yr on $100K home). Not a dollar exemption but a tax rate reduction.',
    seniorExemption: 'Michigan Homestead Property Tax Credit: up to $1,800 refundable credit (income-based, lower limits for seniors). Enhanced at 65+.',
    veteranExemption: 'Disabled veterans (100%): full property tax exemption on homestead.',
    disabilityExemption: 'Totally disabled: Homestead Credit income limits waived.',
    assessmentCap: 'Proposal A (1994): taxable value capped at 5%/year or inflation (whichever is less) until sale.',
    filingProcess: 'File Form 2368 (PRE) with assessor. Form MI-1040CR for Homestead Credit.',
    notes: 'Michigan PRE is a RATE exemption (no school tax on primary home) — very different from dollar exemptions elsewhere. Prop A caps at 5%/inflation.' },

  { slug: 'minnesota', hasHomestead: true, homesteadBase: 30400,
    homesteadDescription: 'Minnesota Homestead Market Value Exclusion: exempts up to $30,400 of value (formula: 40% of first $76K value, reducing above). Applied to primary residence.',
    seniorExemption: 'Senior Citizen Property Tax Deferral: 65+ with income under $96,000 can defer taxes to estate (not exempt).',
    veteranExemption: 'Disabled veterans: $150,000 market value exclusion (70%-99% disability) or $300,000 (100% disability).',
    disabilityExemption: 'Blind/disabled persons: reduction in net tax capacity.',
    assessmentCap: null, filingProcess: 'File Homestead Application (HS-250) with county assessor.',
    notes: 'Minnesota uses "market value exclusion" rather than simple exemption. Veterans get very large exclusion ($300K for 100%).' },

  { slug: 'mississippi', hasHomestead: true, homesteadBase: 7500,
    homesteadDescription: 'Mississippi Homestead Exemption: $7,500 off assessed value (first $300 tax bill reimbursed by state for regular homestead).',
    seniorExemption: 'Over 65 / Disabled: Full homestead exemption on first $75,000 of true value (essentially property tax-free up to $75K).',
    veteranExemption: 'Disabled veterans (100% service-connected): full homestead exemption.',
    disabilityExemption: 'Totally disabled: matches senior exemption ($75K true value tax-free).',
    assessmentCap: null, filingProcess: 'File Homestead Exemption Application with county tax assessor by April 1.',
    notes: 'Mississippi\'s senior/disabled benefit ($75K value exempt) is very generous — most seniors pay little/no property tax.' },

  { slug: 'missouri', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'Missouri has no general homestead exemption but offers Property Tax Credit (Circuit Breaker) for seniors/disabled.',
    seniorExemption: 'Property Tax Credit: up to $1,100 for homeowners 65+ with income under $30,000 (2025). Circuit Breaker for renters too.',
    veteranExemption: 'Disabled Prisoners of War: full exemption. Other veterans: $400 credit via Circuit Breaker.',
    disabilityExemption: 'Totally disabled: same Circuit Breaker eligibility as seniors.',
    assessmentCap: null, filingProcess: 'File Form MO-PTC with state Department of Revenue.',
    notes: 'Missouri\'s Circuit Breaker is primary relief — targeted at low-income elderly/disabled. No broad homestead for all homeowners.' },

  { slug: 'montana', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'Montana has no general homestead exemption. Property Tax Assistance Program (PTAP) and Elderly Homeowner Credit provide relief.',
    seniorExemption: 'Elderly Homeowner Credit: up to $1,150 refundable credit for 62+ with income under $55,000 (2025).',
    veteranExemption: 'Disabled Veterans: 50-100% reduction in taxable value based on income (under $56K single).',
    disabilityExemption: 'Totally disabled: PTAP reduces taxable value 30-80% based on income.',
    assessmentCap: null, filingProcess: 'Apply through Department of Revenue (Form PTAP-D).',
    notes: 'Montana 2023 reappraisal caused large tax increases — more relief programs under development.' },

  { slug: 'nebraska', hasHomestead: true, homesteadBase: 40000,
    homesteadDescription: 'Nebraska Homestead Exemption: 100% of home value exempt up to $40,000 for qualifying applicants (seniors, disabled, veterans — all income-based).',
    seniorExemption: '65+ qualifies for income-based exemption: 100% exempt below certain income, sliding down to 0% above max.',
    veteranExemption: 'Disabled veterans: 100% exempt regardless of income (100% service-connected).',
    disabilityExemption: 'Totally disabled: same income-based structure as seniors.',
    assessmentCap: null, filingProcess: 'File Form 458 with county assessor annually by June 30.',
    notes: 'Nebraska homestead is narrow (income-qualified, 65+/disabled/veteran only) but 100% exemption is very valuable when qualified.' },

  { slug: 'nevada', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'Nevada has no homestead property tax exemption. Tax cap of 3%/year for primary residences is primary benefit.',
    seniorExemption: 'Senior Citizen Property Tax Assistance: rebate for 62+ with income under $34,500 (2025).',
    veteranExemption: 'Veteran exemption: $3,410 (2025, inflation-adjusted). Disabled veterans: $17,050-$34,100 based on disability %.',
    disabilityExemption: 'Surviving spouse of veteran: $1,705 exemption.',
    assessmentCap: '3% annual tax increase cap for primary residences (8% for other properties).',
    filingProcess: 'Apply with county assessor for veteran exemption.',
    notes: 'Nevada 3%/year tax cap on primary residences is a de-facto homestead protection — long-term homeowners pay far less than market.' },

  { slug: 'new-hampshire', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'New Hampshire has no homestead property tax exemption. Limited relief through elderly exemption and veteran credit.',
    seniorExemption: 'Elderly Exemption: $25,000-$50,000+ (varies by town, income-based). Towns set amounts per RSA 72:39-a.',
    veteranExemption: 'Standard Veterans Credit: $50-$750 (town discretion). Disabled veterans: $700-$4,000.',
    disabilityExemption: 'Disabled person exemption: $10,000 typical (town-specific).',
    assessmentCap: null, filingProcess: 'Apply with local Selectmen/Assessor (Form PA-29).',
    notes: 'NH has no state income tax but very high property taxes. Relief is town-dependent — verify with local Selectmen.' },

  { slug: 'new-jersey', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'New Jersey has no classic homestead exemption. ANCHOR Property Tax Relief Program replaced Homestead Rebate in 2023.',
    seniorExemption: 'Senior Freeze (PTR): reimburses property tax increases above base year for 65+ with income under $163,050 (2024).',
    veteranExemption: '$250 annual deduction for wartime veterans. Disabled veterans (100% service-connected): full exemption.',
    disabilityExemption: 'Totally disabled veterans match 100% disabled veteran rate.',
    assessmentCap: null, filingProcess: 'File Form PTR-1 for Senior Freeze; ANCHOR filed separately annually.',
    notes: 'NJ has the highest effective property tax rate in the US. Senior Freeze (PTR) is most valuable relief — reimburses above base year.' },

  { slug: 'new-mexico', hasHomestead: true, homesteadBase: 2000,
    homesteadDescription: 'New Mexico Head of Family Exemption: $2,000 off assessed value. Auto-applied to primary residence.',
    seniorExemption: 'Value Freeze for 65+: income under $44,700 (2025) freezes assessed value. Property Tax Rebate for seniors up to $250.',
    veteranExemption: 'Veteran Exemption: $4,000 off assessed value. Disabled veterans (100%): full property tax exemption.',
    disabilityExemption: 'Totally disabled: matches veteran exemption structure.',
    assessmentCap: '3% annual cap on residential property tax increases (primary residence only).',
    filingProcess: 'File with county assessor (one-time for head-of-family, annual for senior freeze).',
    notes: 'New Mexico has 3% cap on residential tax increases plus senior value freeze — strong long-term protection.' },

  { slug: 'new-york', hasHomestead: true, homesteadBase: 30000,
    homesteadDescription: 'New York STAR Program: Basic STAR exempts $30,000 of home value from school tax (income under $500K). Enhanced STAR: $81,400 (2025) for 65+ with income under $98,700.',
    seniorExemption: 'Enhanced STAR: $81,400 school tax exemption + local Senior Citizens Exemption (50% reduction for low-income 65+).',
    veteranExemption: 'Alternative Veterans Exemption: 15% reduction on assessed value (25% for combat vets, 50% for disabled). Cold War Veterans Exemption (10%-15%).',
    disabilityExemption: 'Persons with Disabilities and Limited Incomes Exemption: 50% reduction (income under $58,400 for 2025).',
    assessmentCap: null, filingProcess: 'Register with NYS Department of Taxation (one-time for STAR). Local exemptions filed with town assessor.',
    notes: 'STAR is unique — school tax exemption, not full property tax. Combined Basic STAR + veteran + senior exemptions can significantly reduce bills in high-tax downstate NY.' },

  { slug: 'north-carolina', hasHomestead: true, homesteadBase: 25000,
    homesteadDescription: 'North Carolina Homestead Exclusion for Elderly/Disabled: $25,000 or 50% of appraised value (whichever is greater) for 65+/disabled with income under $37,900 (2025).',
    seniorExemption: 'Elderly/Disabled Homestead Exclusion (described above). Property Tax Circuit Breaker: caps property tax at 4-5% of income.',
    veteranExemption: 'Disabled veterans (100% service-connected): $45,000 exclusion, no income limit.',
    disabilityExemption: 'Permanently disabled: same as senior exclusion (income-qualified).',
    assessmentCap: null, filingProcess: 'File Form AV-9 (Homestead) with county assessor.',
    notes: 'NC\'s elderly/disabled exclusion is strongly income-tested. Disabled Veterans ($45K) has no income limit — most valuable NC benefit for qualifying veterans.' },

  { slug: 'north-dakota', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'North Dakota has no general homestead exemption. Homestead Tax Credit provides income-based relief for seniors/disabled.',
    seniorExemption: 'Homestead Tax Credit: reduces taxable value by 20-100% based on income (65+ with income under $74,950 single for 2025 qualifies for some credit).',
    veteranExemption: 'Disabled Veterans Credit: 100% disabled veterans get full property tax exemption on homestead.',
    disabilityExemption: 'Totally disabled: same as senior Homestead Tax Credit.',
    assessmentCap: null, filingProcess: 'Apply with county treasurer annually (income-verified).',
    notes: 'North Dakota\'s Homestead Tax Credit is income-graduated (stronger relief at lower incomes). Full exemption for 100% disabled veterans.' },

  { slug: 'ohio', hasHomestead: true, homesteadBase: 26200,
    homesteadDescription: 'Ohio Homestead Exemption: $26,200 off market value ($9,170 off assessed value since OH taxes 35% of market) for 65+ or totally disabled with household income under $39,500 (2025).',
    seniorExemption: '$26,200 exemption for 65+ (income-qualified). Enhanced exemption for disabled veterans.',
    veteranExemption: 'Disabled Veterans Exemption: $52,400 off market value ($18,340 assessed) for 100% service-connected. No income limit.',
    disabilityExemption: 'Totally disabled: same as senior exemption ($26,200 market value).',
    assessmentCap: null, filingProcess: 'File Form DTE 105A with county auditor.',
    notes: 'Ohio senior exemption income-tested ($39,500 limit). Disabled Veterans ($52,400, no income cap) is better benefit when qualified.' },

  { slug: 'oklahoma', hasHomestead: true, homesteadBase: 1000,
    homesteadDescription: 'Oklahoma Homestead Exemption: $1,000 off assessed value. Additional Homestead Exemption: $1,000 for income under $25,000 (total $2,000).',
    seniorExemption: 'Senior Valuation Limitation (65+ with income under $85,300 for 2025): freezes assessed value at age 65.',
    veteranExemption: 'Disabled Veterans (100% service-connected): 100% exemption on homestead, no income limit.',
    disabilityExemption: 'Surviving spouse of disabled veteran retains full exemption.',
    assessmentCap: '3% annual cap on assessed value increases for homesteaded residential property (5% for non-homestead).',
    filingProcess: 'File Form OTC 921 with county assessor (one-time).',
    notes: 'Oklahoma\'s Senior Valuation Freeze is very valuable over time — effectively caps assessment at 65 forever.' },

  { slug: 'oregon', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'Oregon has no general homestead property tax exemption. Measure 50 capped assessed value growth at 3%/year — de-facto homeowner protection.',
    seniorExemption: 'Senior/Disabled Property Tax Deferral: 62+ with income under $57,500 (2025) can defer (not exempt) property taxes to estate.',
    veteranExemption: 'Disabled Veterans Exemption: $29,753 (2025) off assessed value for 40%+ disability. Increases to $35,704 for surviving spouses.',
    disabilityExemption: 'Totally disabled: Property Tax Deferral eligibility.',
    assessmentCap: 'Measure 50 (1997): assessed value growth limited to 3%/year.',
    filingProcess: 'File Form 150-310-085 for veteran exemption with county assessor.',
    notes: 'Measure 50 is Oregon\'s defining feature — caps assessment at 3%/year, diverging dramatically from market value over time.' },

  { slug: 'pennsylvania', hasHomestead: true, homesteadBase: 30000,
    homesteadDescription: 'Pennsylvania Homestead/Farmstead Exclusion: up to 50% of median assessed value exempt (varies by school district, commonly $30,000-$50,000).',
    seniorExemption: 'PA Property Tax/Rent Rebate Program: up to $1,000 (seniors 65+, income under $45,000 — expanded 2024).',
    veteranExemption: 'Disabled veterans (100% service-connected): full property tax exemption if income under $108,046 (2025).',
    disabilityExemption: 'Blind Veteran: full exemption similar to 100% disabled.',
    assessmentCap: null, filingProcess: 'File Homestead Exclusion Application with county assessor (school districts approve amounts).',
    notes: 'PA Homestead is DISTRICT-administered — amounts and eligibility vary by school district. Rebate program targets low-income seniors.' },

  { slug: 'rhode-island', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'Rhode Island has no state homestead exemption. Municipal exemptions vary widely (Providence 45%, others different amounts).',
    seniorExemption: 'Senior exemption varies by city (Providence: 50%+). Elderly Circuit Breaker: credit up to $600 income-based.',
    veteranExemption: 'Veterans Exemption: $1,000-$10,000 assessed value (town-specific). Totally Disabled Veterans: additional $1,000-$20,000.',
    disabilityExemption: 'Totally disabled: usually matches senior exemption rates in most cities.',
    assessmentCap: null, filingProcess: 'Apply with city/town assessor (timing varies).',
    notes: 'Rhode Island exemptions are entirely MUNICIPAL — Providence, Warwick, Cranston, etc. all different. Check specific city.' },

  { slug: 'south-carolina', hasHomestead: true, homesteadBase: 50000,
    homesteadDescription: 'South Carolina Homestead Exemption: $50,000 off fair market value for homeowners 65+/totally disabled/legally blind. 4% assessment ratio for primary residence (vs 6% for other).',
    seniorExemption: 'Homestead Exemption above ($50K). 4% primary residence assessment automatic.',
    veteranExemption: 'Disabled Veterans (100% service-connected): full property tax exemption.',
    disabilityExemption: 'Totally disabled / legally blind: $50,000 homestead exemption (non-income-tested).',
    assessmentCap: '15% cap on reassessment increases (5-year reassessment cycle, increase capped at 15% over whole cycle).',
    filingProcess: 'File Homestead Exemption form with county auditor.',
    notes: 'SC benefits stack: 4% residential assessment + $50K homestead for 65+/disabled/blind = very low effective property tax.' },

  { slug: 'south-dakota', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'South Dakota has no general homestead exemption. Elderly and Disabled Property Tax Program provides freeze/refund.',
    seniorExemption: 'Assessment Freeze for elderly/disabled: 65+ (or disabled) with income under $35,473 (single, 2025) freezes assessed value.',
    veteranExemption: 'Disabled Veterans (100% service-connected): up to $150,000 of assessed value exempt.',
    disabilityExemption: 'Totally disabled: eligible for assessment freeze.',
    assessmentCap: null, filingProcess: 'File with county treasurer annually.',
    notes: 'SD Property Tax Reduction is income-tested. Disabled Veterans exemption ($150K) has no income test.' },

  { slug: 'tennessee', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'Tennessee has no general homestead property tax exemption. Tax relief programs target elderly, disabled, and disabled veterans.',
    seniorExemption: 'Property Tax Relief: reimburses all or part of state portion of tax for 65+/disabled (income under $33,460 for 2025).',
    veteranExemption: 'Disabled Veterans Property Tax Relief: full state tax relief on homes up to $175,000 (value threshold).',
    disabilityExemption: 'Totally disabled: same as senior relief.',
    assessmentCap: null, filingProcess: 'Apply with county trustee annually.',
    notes: 'Tennessee Property Tax Relief is a RELIEF CHECK from the state (not direct exemption). Disabled Veterans most generous.' },

  { slug: 'texas', hasHomestead: true, homesteadBase: 100000,
    homesteadDescription: 'Texas School Homestead Exemption: $100,000 off school tax value (raised from $40K in 2023 via Prop 4). County/city/special district exemptions add up to $20,000 more.',
    seniorExemption: 'Over-65 Exemption: additional $10,000 off school tax value (total $110,000). Tax ceiling freezes school tax at level paid year of qualification.',
    veteranExemption: 'Disabled Veterans: $5,000-$12,000 off based on disability %. 100% disabled: full exemption on homestead.',
    disabilityExemption: 'Disabled Persons Exemption: $10,000 off school tax (same as senior, income-qualified).',
    assessmentCap: '10% annual cap on homestead appraised value increases.',
    filingProcess: 'File Form 50-114 with county appraisal district (one-time for homestead).',
    notes: 'Texas homestead massively expanded 2023 ($40K → $100K). Combined with 10% cap + senior freeze = strong long-term homeowner protection.' },

  { slug: 'utah', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'Utah has no general homestead exemption but primary residences are assessed at 55% of market value (non-residential at 100%), effectively a 45% exemption.',
    seniorExemption: 'Circuit Breaker: 65+ with income under $38,369 (2025) get Indigent Abatement up to $1,259.',
    veteranExemption: 'Veterans with Disability Exemption: up to $505,548 of residence value (2025, 100% disabled).',
    disabilityExemption: 'Blind exemption: $11,500.',
    assessmentCap: null, filingProcess: 'Apply with county assessor for abatement/exemption.',
    notes: 'Utah\'s 55% residential assessment ratio is its primary homeowner benefit — automatic, no filing. Veteran exemption for disabled is very valuable.' },

  { slug: 'vermont', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'Vermont Homestead Declaration required annually. Homestead education property tax based on income (adjustable via Household Income Credit).',
    seniorExemption: 'Property Tax Credit: income-based adjustment for education portion of tax. 65+ have specific veteran/disability additions.',
    veteranExemption: 'Disabled Veterans (50%+ service-connected): $10,000 exemption. 100%: full exemption up to $40,000.',
    disabilityExemption: 'Totally disabled qualify for Property Tax Credit income limits.',
    assessmentCap: null, filingProcess: 'File Homestead Declaration (HS-122) annually with state tax form.',
    notes: 'Vermont\'s primary homeowner benefit is INCOME-SENSITIVITY for education tax via Property Tax Credit — not a dollar exemption.' },

  { slug: 'virginia', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'Virginia has no state homestead exemption. All relief is LOCAL (counties/cities set exemption amounts).',
    seniorExemption: 'County-administered Real Estate Tax Relief for elderly/disabled — amounts and income limits vary (Fairfax: $75K income limit, exemption up to $340K value).',
    veteranExemption: 'Disabled Veterans (100% service-connected): full state-mandated exemption on primary residence.',
    disabilityExemption: 'Totally disabled: county-specific, usually matches senior rules.',
    assessmentCap: null, filingProcess: 'Apply with local city/county Commissioner of Revenue.',
    notes: 'Virginia delegates most property tax exemption authority to localities. Fairfax, Arlington, Loudoun each have very different rules.' },

  { slug: 'washington', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'Washington has no general homestead exemption. Senior/Disabled Property Tax Exemption program provides income-based relief.',
    seniorExemption: 'Property Tax Exemption: 61+ (or disabled) with income under $60,000-$84,000 (county-varying for 2025) get exemption ranging 50%-100% of tax.',
    veteranExemption: 'Disabled Veterans (80%+ service-connected): same as senior income-based exemption.',
    disabilityExemption: 'Totally disabled: full eligibility for program.',
    assessmentCap: null, filingProcess: 'File with county assessor annually (income-verified).',
    notes: 'Washington limits property tax levy growth to 1%/year (state law) — de facto cap on aggregate tax. Individual relief income-tested.' },

  { slug: 'west-virginia', hasHomestead: true, homesteadBase: 20000,
    homesteadDescription: 'West Virginia Homestead Exemption: $20,000 off assessed value for homeowners 65+ or totally disabled.',
    seniorExemption: '$20,000 exemption at 65 (or disabled) — no income test required.',
    veteranExemption: 'Disabled Veterans (100% service-connected): full property tax exemption.',
    disabilityExemption: 'Totally disabled: same $20,000 exemption as seniors.',
    assessmentCap: null, filingProcess: 'File with county assessor (one-time).',
    notes: 'West Virginia\'s $20K senior/disabled exemption has NO income test — one of few states offering this without means-testing.' },

  { slug: 'wisconsin', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'Wisconsin has no homestead property tax exemption but offers generous Homestead Tax Credit (refundable income tax credit based on property tax paid).',
    seniorExemption: 'Homestead Credit: income under $24,680 (2025) qualifies for credit up to $1,168. Higher limits for 62+.',
    veteranExemption: 'Veterans and Surviving Spouses Property Tax Credit: refundable income tax credit equal to property tax paid (100% disabled veterans).',
    disabilityExemption: 'Totally disabled: same as senior Homestead Credit eligibility.',
    assessmentCap: null, filingProcess: 'File Schedule H with state income tax return.',
    notes: 'Wisconsin Veterans Credit is unique — refunds 100% of property tax paid via state income tax credit (most valuable vet benefit in US).' },

  { slug: 'wyoming', hasHomestead: true, homesteadBase: 0,
    homesteadDescription: 'Wyoming has no general homestead property tax exemption. Long-term homeowner exemption (new 2024) and senior refunds exist.',
    seniorExemption: 'Property Tax Refund Program: 65+ with income under $47,000 (single, 2025) refunded 75% of property tax paid.',
    veteranExemption: 'Veterans Exemption: $3,000 assessed value reduction. Disabled Veterans (100%): increased amount.',
    disabilityExemption: 'Disabled: Property Tax Refund eligibility.',
    assessmentCap: 'Long-term Homeowner Exemption (2024): 50% of fair market value exempt for homeowners 65+ who owned 25+ years.',
    filingProcess: 'Apply with Wyoming Department of Revenue annually.',
    notes: 'Wyoming Long-Term Homeowner Exemption (2024) is brand new — 25+ year residents at 65 get 50% off. Very generous.' },
];

export function getStateExemptionData(slug: string): StateExemptionData | undefined {
  return stateExemptionData.find((s) => s.slug === slug);
}
